const { createSimpleCrudService } = require('./simpleCrudFactory');

module.exports = createSimpleCrudService({
  table: 'vehicles',
  entityName: 'Vehicle',
  searchColumns: ['reg_number', 'model', 'vin'],
  filterColumns: ['carrier_id', 'terminal_id', 'vehicle_type_id'],
  columns: [
    'carrier_id',
    'fleet_group_id',
    'vehicle_type_id',
    'terminal_id',
    'reg_number',
    'license_number',
    'license_state_id',
    'vin',
    'make',
    'model',
    'year',
    'integration_id',
    'notes',
    'tank_capacity',
    'average_mpg',
    'def_level',
    'sold_date',
    'sold_price',
    'starting_mileage',
    'current_mileage',
    'mortgage_cost',
    'annual_insurance_cost',
    'annual_plate_cost',
    'insurance_renewal_date',
    'last_maintenance_date',
    'inspection_expiration',
    'in_service_from',
    'registration_date',
    'reg_expiry_date',
    'purchase_date',
    'prepass_number',
    'is_owner_operated',
    'is_camera_installed',
    'is_apu_installed',
    'is_active',
    'is_lease',
    'lease_carrier_id',
    'lease_start_date',
    'lease_end_date',
    'expire_date',
    'track_name'
  ],
  requiredFields: ['reg_number'],
  isActiveColumn: 'is_active',
  orderBy: 'reg_number'
});
